/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: server.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "server.pb-c.h"
void   srvr_simple_descriptor_t__init
                     (SrvrSimpleDescriptorT         *message)
{
  static SrvrSimpleDescriptorT init_value = SRVR_SIMPLE_DESCRIPTOR_T__INIT;
  *message = init_value;
}
size_t srvr_simple_descriptor_t__get_packed_size
                     (const SrvrSimpleDescriptorT *message)
{
  assert(message->base.descriptor == &srvr_simple_descriptor_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_simple_descriptor_t__pack
                     (const SrvrSimpleDescriptorT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_simple_descriptor_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_simple_descriptor_t__pack_to_buffer
                     (const SrvrSimpleDescriptorT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_simple_descriptor_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrSimpleDescriptorT *
       srvr_simple_descriptor_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrSimpleDescriptorT *)
     protobuf_c_message_unpack (&srvr_simple_descriptor_t__descriptor,
                                allocator, len, data);
}
void   srvr_simple_descriptor_t__free_unpacked
                     (SrvrSimpleDescriptorT *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_simple_descriptor_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_device_info_t__init
                     (SrvrDeviceInfoT         *message)
{
  static SrvrDeviceInfoT init_value = SRVR_DEVICE_INFO_T__INIT;
  *message = init_value;
}
size_t srvr_device_info_t__get_packed_size
                     (const SrvrDeviceInfoT *message)
{
  assert(message->base.descriptor == &srvr_device_info_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_device_info_t__pack
                     (const SrvrDeviceInfoT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_device_info_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_device_info_t__pack_to_buffer
                     (const SrvrDeviceInfoT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_device_info_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrDeviceInfoT *
       srvr_device_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrDeviceInfoT *)
     protobuf_c_message_unpack (&srvr_device_info_t__descriptor,
                                allocator, len, data);
}
void   srvr_device_info_t__free_unpacked
                     (SrvrDeviceInfoT *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_device_info_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_ieee_address_req__init
                     (SrvrGetIeeeAddressReq         *message)
{
  static SrvrGetIeeeAddressReq init_value = SRVR_GET_IEEE_ADDRESS_REQ__INIT;
  *message = init_value;
}
size_t srvr_get_ieee_address_req__get_packed_size
                     (const SrvrGetIeeeAddressReq *message)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_ieee_address_req__pack
                     (const SrvrGetIeeeAddressReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_ieee_address_req__pack_to_buffer
                     (const SrvrGetIeeeAddressReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetIeeeAddressReq *
       srvr_get_ieee_address_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetIeeeAddressReq *)
     protobuf_c_message_unpack (&srvr_get_ieee_address_req__descriptor,
                                allocator, len, data);
}
void   srvr_get_ieee_address_req__free_unpacked
                     (SrvrGetIeeeAddressReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_ieee_address_cnf__init
                     (SrvrGetIeeeAddressCnf         *message)
{
  static SrvrGetIeeeAddressCnf init_value = SRVR_GET_IEEE_ADDRESS_CNF__INIT;
  *message = init_value;
}
size_t srvr_get_ieee_address_cnf__get_packed_size
                     (const SrvrGetIeeeAddressCnf *message)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_ieee_address_cnf__pack
                     (const SrvrGetIeeeAddressCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_ieee_address_cnf__pack_to_buffer
                     (const SrvrGetIeeeAddressCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetIeeeAddressCnf *
       srvr_get_ieee_address_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetIeeeAddressCnf *)
     protobuf_c_message_unpack (&srvr_get_ieee_address_cnf__descriptor,
                                allocator, len, data);
}
void   srvr_get_ieee_address_cnf__free_unpacked
                     (SrvrGetIeeeAddressCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_ieee_address_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_short_address_req__init
                     (SrvrGetShortAddressReq         *message)
{
  static SrvrGetShortAddressReq init_value = SRVR_GET_SHORT_ADDRESS_REQ__INIT;
  *message = init_value;
}
size_t srvr_get_short_address_req__get_packed_size
                     (const SrvrGetShortAddressReq *message)
{
  assert(message->base.descriptor == &srvr_get_short_address_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_short_address_req__pack
                     (const SrvrGetShortAddressReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_short_address_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_short_address_req__pack_to_buffer
                     (const SrvrGetShortAddressReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_short_address_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetShortAddressReq *
       srvr_get_short_address_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetShortAddressReq *)
     protobuf_c_message_unpack (&srvr_get_short_address_req__descriptor,
                                allocator, len, data);
}
void   srvr_get_short_address_req__free_unpacked
                     (SrvrGetShortAddressReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_short_address_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_short_address_cnf__init
                     (SrvrGetShortAddressCnf         *message)
{
  static SrvrGetShortAddressCnf init_value = SRVR_GET_SHORT_ADDRESS_CNF__INIT;
  *message = init_value;
}
size_t srvr_get_short_address_cnf__get_packed_size
                     (const SrvrGetShortAddressCnf *message)
{
  assert(message->base.descriptor == &srvr_get_short_address_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_short_address_cnf__pack
                     (const SrvrGetShortAddressCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_short_address_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_short_address_cnf__pack_to_buffer
                     (const SrvrGetShortAddressCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_short_address_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetShortAddressCnf *
       srvr_get_short_address_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetShortAddressCnf *)
     protobuf_c_message_unpack (&srvr_get_short_address_cnf__descriptor,
                                allocator, len, data);
}
void   srvr_get_short_address_cnf__free_unpacked
                     (SrvrGetShortAddressCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_short_address_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_device_info_req__init
                     (SrvrGetDeviceInfoReq         *message)
{
  static SrvrGetDeviceInfoReq init_value = SRVR_GET_DEVICE_INFO_REQ__INIT;
  *message = init_value;
}
size_t srvr_get_device_info_req__get_packed_size
                     (const SrvrGetDeviceInfoReq *message)
{
  assert(message->base.descriptor == &srvr_get_device_info_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_device_info_req__pack
                     (const SrvrGetDeviceInfoReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_device_info_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_device_info_req__pack_to_buffer
                     (const SrvrGetDeviceInfoReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_device_info_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetDeviceInfoReq *
       srvr_get_device_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetDeviceInfoReq *)
     protobuf_c_message_unpack (&srvr_get_device_info_req__descriptor,
                                allocator, len, data);
}
void   srvr_get_device_info_req__free_unpacked
                     (SrvrGetDeviceInfoReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_device_info_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_device_info_cnf__init
                     (SrvrGetDeviceInfoCnf         *message)
{
  static SrvrGetDeviceInfoCnf init_value = SRVR_GET_DEVICE_INFO_CNF__INIT;
  *message = init_value;
}
size_t srvr_get_device_info_cnf__get_packed_size
                     (const SrvrGetDeviceInfoCnf *message)
{
  assert(message->base.descriptor == &srvr_get_device_info_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_device_info_cnf__pack
                     (const SrvrGetDeviceInfoCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_device_info_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_device_info_cnf__pack_to_buffer
                     (const SrvrGetDeviceInfoCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_device_info_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetDeviceInfoCnf *
       srvr_get_device_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetDeviceInfoCnf *)
     protobuf_c_message_unpack (&srvr_get_device_info_cnf__descriptor,
                                allocator, len, data);
}
void   srvr_get_device_info_cnf__free_unpacked
                     (SrvrGetDeviceInfoCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_device_info_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_device_status_req__init
                     (SrvrGetDeviceStatusReq         *message)
{
  static SrvrGetDeviceStatusReq init_value = SRVR_GET_DEVICE_STATUS_REQ__INIT;
  *message = init_value;
}
size_t srvr_get_device_status_req__get_packed_size
                     (const SrvrGetDeviceStatusReq *message)
{
  assert(message->base.descriptor == &srvr_get_device_status_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_device_status_req__pack
                     (const SrvrGetDeviceStatusReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_device_status_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_device_status_req__pack_to_buffer
                     (const SrvrGetDeviceStatusReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_device_status_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetDeviceStatusReq *
       srvr_get_device_status_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetDeviceStatusReq *)
     protobuf_c_message_unpack (&srvr_get_device_status_req__descriptor,
                                allocator, len, data);
}
void   srvr_get_device_status_req__free_unpacked
                     (SrvrGetDeviceStatusReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_device_status_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_get_device_status_cnf__init
                     (SrvrGetDeviceStatusCnf         *message)
{
  static SrvrGetDeviceStatusCnf init_value = SRVR_GET_DEVICE_STATUS_CNF__INIT;
  *message = init_value;
}
size_t srvr_get_device_status_cnf__get_packed_size
                     (const SrvrGetDeviceStatusCnf *message)
{
  assert(message->base.descriptor == &srvr_get_device_status_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_get_device_status_cnf__pack
                     (const SrvrGetDeviceStatusCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_get_device_status_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_get_device_status_cnf__pack_to_buffer
                     (const SrvrGetDeviceStatusCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_get_device_status_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrGetDeviceStatusCnf *
       srvr_get_device_status_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrGetDeviceStatusCnf *)
     protobuf_c_message_unpack (&srvr_get_device_status_cnf__descriptor,
                                allocator, len, data);
}
void   srvr_get_device_status_cnf__free_unpacked
                     (SrvrGetDeviceStatusCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_get_device_status_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_set_device_status_req__init
                     (SrvrSetDeviceStatusReq         *message)
{
  static SrvrSetDeviceStatusReq init_value = SRVR_SET_DEVICE_STATUS_REQ__INIT;
  *message = init_value;
}
size_t srvr_set_device_status_req__get_packed_size
                     (const SrvrSetDeviceStatusReq *message)
{
  assert(message->base.descriptor == &srvr_set_device_status_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_set_device_status_req__pack
                     (const SrvrSetDeviceStatusReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_set_device_status_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_set_device_status_req__pack_to_buffer
                     (const SrvrSetDeviceStatusReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_set_device_status_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrSetDeviceStatusReq *
       srvr_set_device_status_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrSetDeviceStatusReq *)
     protobuf_c_message_unpack (&srvr_set_device_status_req__descriptor,
                                allocator, len, data);
}
void   srvr_set_device_status_req__free_unpacked
                     (SrvrSetDeviceStatusReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_set_device_status_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   srvr_set_device_status_cnf__init
                     (SrvrSetDeviceStatusCnf         *message)
{
  static SrvrSetDeviceStatusCnf init_value = SRVR_SET_DEVICE_STATUS_CNF__INIT;
  *message = init_value;
}
size_t srvr_set_device_status_cnf__get_packed_size
                     (const SrvrSetDeviceStatusCnf *message)
{
  assert(message->base.descriptor == &srvr_set_device_status_cnf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t srvr_set_device_status_cnf__pack
                     (const SrvrSetDeviceStatusCnf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &srvr_set_device_status_cnf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t srvr_set_device_status_cnf__pack_to_buffer
                     (const SrvrSetDeviceStatusCnf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &srvr_set_device_status_cnf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SrvrSetDeviceStatusCnf *
       srvr_set_device_status_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SrvrSetDeviceStatusCnf *)
     protobuf_c_message_unpack (&srvr_set_device_status_cnf__descriptor,
                                allocator, len, data);
}
void   srvr_set_device_status_cnf__free_unpacked
                     (SrvrSetDeviceStatusCnf *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &srvr_set_device_status_cnf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor srvr_simple_descriptor_t__field_descriptors[6] =
{
  {
    "endpointId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrSimpleDescriptorT, endpointid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "profileId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrSimpleDescriptorT, profileid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrSimpleDescriptorT, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceVer",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrSimpleDescriptorT, devicever),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputClusters",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SrvrSimpleDescriptorT, n_inputclusters),
    offsetof(SrvrSimpleDescriptorT, inputclusters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputClusters",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SrvrSimpleDescriptorT, n_outputclusters),
    offsetof(SrvrSimpleDescriptorT, outputclusters),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_simple_descriptor_t__field_indices_by_name[] = {
  2,   /* field[2] = deviceId */
  3,   /* field[3] = deviceVer */
  0,   /* field[0] = endpointId */
  4,   /* field[4] = inputClusters */
  5,   /* field[5] = outputClusters */
  1,   /* field[1] = profileId */
};
static const ProtobufCIntRange srvr_simple_descriptor_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor srvr_simple_descriptor_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "srvrSimpleDescriptor_t",
  "SrvrSimpleDescriptorT",
  "SrvrSimpleDescriptorT",
  "",
  sizeof(SrvrSimpleDescriptorT),
  6,
  srvr_simple_descriptor_t__field_descriptors,
  srvr_simple_descriptor_t__field_indices_by_name,
  1,  srvr_simple_descriptor_t__number_ranges,
  (ProtobufCMessageInit) srvr_simple_descriptor_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor srvr_device_info_t__field_descriptors[6] =
{
  {
    "networkAddress",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrDeviceInfoT, networkaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrDeviceInfoT, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentIeeeAddress",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(SrvrDeviceInfoT, has_parentieeeaddress),
    offsetof(SrvrDeviceInfoT, parentieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manufacturerId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrDeviceInfoT, manufacturerid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "simpleDescList",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SrvrDeviceInfoT, n_simpledesclist),
    offsetof(SrvrDeviceInfoT, simpledesclist),
    &srvr_simple_descriptor_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceStatus",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrDeviceInfoT, devicestatus),
    &srvr_device_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_device_info_t__field_indices_by_name[] = {
  5,   /* field[5] = deviceStatus */
  1,   /* field[1] = ieeeAddress */
  3,   /* field[3] = manufacturerId */
  0,   /* field[0] = networkAddress */
  2,   /* field[2] = parentIeeeAddress */
  4,   /* field[4] = simpleDescList */
};
static const ProtobufCIntRange srvr_device_info_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor srvr_device_info_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "srvrDeviceInfo_t",
  "SrvrDeviceInfoT",
  "SrvrDeviceInfoT",
  "",
  sizeof(SrvrDeviceInfoT),
  6,
  srvr_device_info_t__field_descriptors,
  srvr_device_info_t__field_indices_by_name,
  1,  srvr_device_info_t__number_ranges,
  (ProtobufCMessageInit) srvr_device_info_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_ieee_address_req__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_IEEE_ADDRESS_REQ;
static const ProtobufCFieldDescriptor srvr_get_ieee_address_req__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetIeeeAddressReq, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_ieee_address_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shortAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrGetIeeeAddressReq, shortaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_ieee_address_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = shortAddress */
};
static const ProtobufCIntRange srvr_get_ieee_address_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor srvr_get_ieee_address_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetIeeeAddressReq",
  "SrvrGetIeeeAddressReq",
  "SrvrGetIeeeAddressReq",
  "",
  sizeof(SrvrGetIeeeAddressReq),
  2,
  srvr_get_ieee_address_req__field_descriptors,
  srvr_get_ieee_address_req__field_indices_by_name,
  1,  srvr_get_ieee_address_req__number_ranges,
  (ProtobufCMessageInit) srvr_get_ieee_address_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_ieee_address_cnf__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_IEEE_ADDRESS_CNF;
static const ProtobufCFieldDescriptor srvr_get_ieee_address_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetIeeeAddressCnf, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_ieee_address_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetIeeeAddressCnf, status),
    &srvr_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrGetIeeeAddressCnf, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_ieee_address_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = ieeeAddress */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange srvr_get_ieee_address_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor srvr_get_ieee_address_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetIeeeAddressCnf",
  "SrvrGetIeeeAddressCnf",
  "SrvrGetIeeeAddressCnf",
  "",
  sizeof(SrvrGetIeeeAddressCnf),
  3,
  srvr_get_ieee_address_cnf__field_descriptors,
  srvr_get_ieee_address_cnf__field_indices_by_name,
  1,  srvr_get_ieee_address_cnf__number_ranges,
  (ProtobufCMessageInit) srvr_get_ieee_address_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_short_address_req__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_SHORT_ADDRESS_REQ;
static const ProtobufCFieldDescriptor srvr_get_short_address_req__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetShortAddressReq, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_short_address_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrGetShortAddressReq, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_short_address_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = ieeeAddress */
};
static const ProtobufCIntRange srvr_get_short_address_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor srvr_get_short_address_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetShortAddressReq",
  "SrvrGetShortAddressReq",
  "SrvrGetShortAddressReq",
  "",
  sizeof(SrvrGetShortAddressReq),
  2,
  srvr_get_short_address_req__field_descriptors,
  srvr_get_short_address_req__field_indices_by_name,
  1,  srvr_get_short_address_req__number_ranges,
  (ProtobufCMessageInit) srvr_get_short_address_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_short_address_cnf__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_SHORT_ADDRESS_CNF;
static const ProtobufCFieldDescriptor srvr_get_short_address_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetShortAddressCnf, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_short_address_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetShortAddressCnf, status),
    &srvr_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shortAddress",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SrvrGetShortAddressCnf, shortaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_short_address_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = shortAddress */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange srvr_get_short_address_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor srvr_get_short_address_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetShortAddressCnf",
  "SrvrGetShortAddressCnf",
  "SrvrGetShortAddressCnf",
  "",
  sizeof(SrvrGetShortAddressCnf),
  3,
  srvr_get_short_address_cnf__field_descriptors,
  srvr_get_short_address_cnf__field_indices_by_name,
  1,  srvr_get_short_address_cnf__number_ranges,
  (ProtobufCMessageInit) srvr_get_short_address_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_device_info_req__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_DEVICE_INFO_REQ;
static const ProtobufCFieldDescriptor srvr_get_device_info_req__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceInfoReq, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_device_info_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceInfoReq, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_device_info_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = ieeeAddress */
};
static const ProtobufCIntRange srvr_get_device_info_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor srvr_get_device_info_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetDeviceInfoReq",
  "SrvrGetDeviceInfoReq",
  "SrvrGetDeviceInfoReq",
  "",
  sizeof(SrvrGetDeviceInfoReq),
  2,
  srvr_get_device_info_req__field_descriptors,
  srvr_get_device_info_req__field_indices_by_name,
  1,  srvr_get_device_info_req__number_ranges,
  (ProtobufCMessageInit) srvr_get_device_info_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_device_info_cnf__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_DEVICE_INFO_CNF;
static const ProtobufCFieldDescriptor srvr_get_device_info_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceInfoCnf, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_device_info_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceInfoCnf, status),
    &srvr_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceInfo",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceInfoCnf, deviceinfo),
    &srvr_device_info_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_device_info_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = deviceInfo */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange srvr_get_device_info_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor srvr_get_device_info_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetDeviceInfoCnf",
  "SrvrGetDeviceInfoCnf",
  "SrvrGetDeviceInfoCnf",
  "",
  sizeof(SrvrGetDeviceInfoCnf),
  3,
  srvr_get_device_info_cnf__field_descriptors,
  srvr_get_device_info_cnf__field_indices_by_name,
  1,  srvr_get_device_info_cnf__number_ranges,
  (ProtobufCMessageInit) srvr_get_device_info_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_device_status_req__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_DEVICE_STATUS_REQ;
static const ProtobufCFieldDescriptor srvr_get_device_status_req__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceStatusReq, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_device_status_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceStatusReq, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_device_status_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = ieeeAddress */
};
static const ProtobufCIntRange srvr_get_device_status_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor srvr_get_device_status_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetDeviceStatusReq",
  "SrvrGetDeviceStatusReq",
  "SrvrGetDeviceStatusReq",
  "",
  sizeof(SrvrGetDeviceStatusReq),
  2,
  srvr_get_device_status_req__field_descriptors,
  srvr_get_device_status_req__field_indices_by_name,
  1,  srvr_get_device_status_req__number_ranges,
  (ProtobufCMessageInit) srvr_get_device_status_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_get_device_status_cnf__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_GET_DEVICE_STATUS_CNF;
static const ProtobufCFieldDescriptor srvr_get_device_status_cnf__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceStatusCnf, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_get_device_status_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceStatusCnf, status),
    &srvr_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceStatus",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrGetDeviceStatusCnf, devicestatus),
    &srvr_device_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_get_device_status_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = deviceStatus */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange srvr_get_device_status_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor srvr_get_device_status_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrGetDeviceStatusCnf",
  "SrvrGetDeviceStatusCnf",
  "SrvrGetDeviceStatusCnf",
  "",
  sizeof(SrvrGetDeviceStatusCnf),
  3,
  srvr_get_device_status_cnf__field_descriptors,
  srvr_get_device_status_cnf__field_indices_by_name,
  1,  srvr_get_device_status_cnf__number_ranges,
  (ProtobufCMessageInit) srvr_get_device_status_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_set_device_status_req__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_SET_DEVICE_STATUS_REQ;
static const ProtobufCFieldDescriptor srvr_set_device_status_req__field_descriptors[3] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrSetDeviceStatusReq, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_set_device_status_req__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieeeAddress",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(SrvrSetDeviceStatusReq, ieeeaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceStatus",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrSetDeviceStatusReq, devicestatus),
    &srvr_device_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_set_device_status_req__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  2,   /* field[2] = deviceStatus */
  1,   /* field[1] = ieeeAddress */
};
static const ProtobufCIntRange srvr_set_device_status_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor srvr_set_device_status_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrSetDeviceStatusReq",
  "SrvrSetDeviceStatusReq",
  "SrvrSetDeviceStatusReq",
  "",
  sizeof(SrvrSetDeviceStatusReq),
  3,
  srvr_set_device_status_req__field_descriptors,
  srvr_set_device_status_req__field_indices_by_name,
  1,  srvr_set_device_status_req__number_ranges,
  (ProtobufCMessageInit) srvr_set_device_status_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const SrvrCmdIdT srvr_set_device_status_cnf__cmd_id__default_value = SRVR_CMD_ID_T__SRVR_SET_DEVICE_STATUS_CNF;
static const ProtobufCFieldDescriptor srvr_set_device_status_cnf__field_descriptors[2] =
{
  {
    "cmdId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrSetDeviceStatusCnf, cmdid),
    &srvr_cmd_id_t__descriptor,
    &srvr_set_device_status_cnf__cmd_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SrvrSetDeviceStatusCnf, status),
    &srvr_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned srvr_set_device_status_cnf__field_indices_by_name[] = {
  0,   /* field[0] = cmdId */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange srvr_set_device_status_cnf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor srvr_set_device_status_cnf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SrvrSetDeviceStatusCnf",
  "SrvrSetDeviceStatusCnf",
  "SrvrSetDeviceStatusCnf",
  "",
  sizeof(SrvrSetDeviceStatusCnf),
  2,
  srvr_set_device_status_cnf__field_descriptors,
  srvr_set_device_status_cnf__field_indices_by_name,
  1,  srvr_set_device_status_cnf__number_ranges,
  (ProtobufCMessageInit) srvr_set_device_status_cnf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue z_stack_server_sys_id_t__enum_values_by_number[1] =
{
  { "RPC_SYS_PB_SRVR", "Z_STACK_SERVER_SYS_ID_T__RPC_SYS_PB_SRVR", 25 },
};
static const ProtobufCIntRange z_stack_server_sys_id_t__value_ranges[] = {
{25, 0},{0, 1}
};
static const ProtobufCEnumValueIndex z_stack_server_sys_id_t__enum_values_by_name[1] =
{
  { "RPC_SYS_PB_SRVR", 0 },
};
const ProtobufCEnumDescriptor z_stack_server_sys_id_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "zStackServerSysId_t",
  "zStackServerSysId_t",
  "ZStackServerSysIdT",
  "",
  1,
  z_stack_server_sys_id_t__enum_values_by_number,
  1,
  z_stack_server_sys_id_t__enum_values_by_name,
  1,
  z_stack_server_sys_id_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue srvr_cmd_id_t__enum_values_by_number[10] =
{
  { "SRVR_GET_IEEE_ADDRESS_REQ", "SRVR_CMD_ID_T__SRVR_GET_IEEE_ADDRESS_REQ", 0 },
  { "SRVR_GET_IEEE_ADDRESS_CNF", "SRVR_CMD_ID_T__SRVR_GET_IEEE_ADDRESS_CNF", 1 },
  { "SRVR_GET_SHORT_ADDRESS_REQ", "SRVR_CMD_ID_T__SRVR_GET_SHORT_ADDRESS_REQ", 2 },
  { "SRVR_GET_SHORT_ADDRESS_CNF", "SRVR_CMD_ID_T__SRVR_GET_SHORT_ADDRESS_CNF", 3 },
  { "SRVR_GET_DEVICE_INFO_REQ", "SRVR_CMD_ID_T__SRVR_GET_DEVICE_INFO_REQ", 4 },
  { "SRVR_GET_DEVICE_INFO_CNF", "SRVR_CMD_ID_T__SRVR_GET_DEVICE_INFO_CNF", 5 },
  { "SRVR_GET_DEVICE_STATUS_REQ", "SRVR_CMD_ID_T__SRVR_GET_DEVICE_STATUS_REQ", 6 },
  { "SRVR_GET_DEVICE_STATUS_CNF", "SRVR_CMD_ID_T__SRVR_GET_DEVICE_STATUS_CNF", 7 },
  { "SRVR_SET_DEVICE_STATUS_REQ", "SRVR_CMD_ID_T__SRVR_SET_DEVICE_STATUS_REQ", 8 },
  { "SRVR_SET_DEVICE_STATUS_CNF", "SRVR_CMD_ID_T__SRVR_SET_DEVICE_STATUS_CNF", 9 },
};
static const ProtobufCIntRange srvr_cmd_id_t__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex srvr_cmd_id_t__enum_values_by_name[10] =
{
  { "SRVR_GET_DEVICE_INFO_CNF", 5 },
  { "SRVR_GET_DEVICE_INFO_REQ", 4 },
  { "SRVR_GET_DEVICE_STATUS_CNF", 7 },
  { "SRVR_GET_DEVICE_STATUS_REQ", 6 },
  { "SRVR_GET_IEEE_ADDRESS_CNF", 1 },
  { "SRVR_GET_IEEE_ADDRESS_REQ", 0 },
  { "SRVR_GET_SHORT_ADDRESS_CNF", 3 },
  { "SRVR_GET_SHORT_ADDRESS_REQ", 2 },
  { "SRVR_SET_DEVICE_STATUS_CNF", 9 },
  { "SRVR_SET_DEVICE_STATUS_REQ", 8 },
};
const ProtobufCEnumDescriptor srvr_cmd_id_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "srvrCmdId_t",
  "srvrCmdId_t",
  "SrvrCmdIdT",
  "",
  10,
  srvr_cmd_id_t__enum_values_by_number,
  10,
  srvr_cmd_id_t__enum_values_by_name,
  1,
  srvr_cmd_id_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue srvr_device_status_t__enum_values_by_number[4] =
{
  { "DEVICE_OFF_LINE", "SRVR_DEVICE_STATUS_T__DEVICE_OFF_LINE", 0 },
  { "DEVICE_ON_LINE", "SRVR_DEVICE_STATUS_T__DEVICE_ON_LINE", 1 },
  { "DEVICE_REMOVED", "SRVR_DEVICE_STATUS_T__DEVICE_REMOVED", 2 },
  { "DEVICE_NA", "SRVR_DEVICE_STATUS_T__DEVICE_NA", 255 },
};
static const ProtobufCIntRange srvr_device_status_t__value_ranges[] = {
{0, 0},{255, 3},{0, 4}
};
static const ProtobufCEnumValueIndex srvr_device_status_t__enum_values_by_name[4] =
{
  { "DEVICE_NA", 3 },
  { "DEVICE_OFF_LINE", 0 },
  { "DEVICE_ON_LINE", 1 },
  { "DEVICE_REMOVED", 2 },
};
const ProtobufCEnumDescriptor srvr_device_status_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "srvrDeviceStatus_t",
  "srvrDeviceStatus_t",
  "SrvrDeviceStatusT",
  "",
  4,
  srvr_device_status_t__enum_values_by_number,
  4,
  srvr_device_status_t__enum_values_by_name,
  2,
  srvr_device_status_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue srvr_status_t__enum_values_by_number[5] =
{
  { "STATUS_SUCCESS", "SRVR_STATUS_T__STATUS_SUCCESS", 0 },
  { "STATUS_FAILURE", "SRVR_STATUS_T__STATUS_FAILURE", 1 },
  { "STATUS_BUSY", "SRVR_STATUS_T__STATUS_BUSY", 2 },
  { "STATUS_INVALID_PARAMETER", "SRVR_STATUS_T__STATUS_INVALID_PARAMETER", 3 },
  { "STATUS_TIMEOUT", "SRVR_STATUS_T__STATUS_TIMEOUT", 4 },
};
static const ProtobufCIntRange srvr_status_t__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex srvr_status_t__enum_values_by_name[5] =
{
  { "STATUS_BUSY", 2 },
  { "STATUS_FAILURE", 1 },
  { "STATUS_INVALID_PARAMETER", 3 },
  { "STATUS_SUCCESS", 0 },
  { "STATUS_TIMEOUT", 4 },
};
const ProtobufCEnumDescriptor srvr_status_t__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "srvrStatus_t",
  "srvrStatus_t",
  "SrvrStatusT",
  "",
  5,
  srvr_status_t__enum_values_by_number,
  5,
  srvr_status_t__enum_values_by_name,
  1,
  srvr_status_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
