/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nwkmgr.proto */

#ifndef PROTOBUF_C_nwkmgr_2eproto__INCLUDED
#define PROTOBUF_C_nwkmgr_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

typedef struct _NwkGetGwEndpointInfoReq NwkGetGwEndpointInfoReq;
typedef struct _NwkAddressStructT NwkAddressStructT;
typedef struct _NwkSimpleDescriptorT NwkSimpleDescriptorT;
typedef struct _NwkBindRecT NwkBindRecT;
typedef struct _NwkDeviceInfoT NwkDeviceInfoT;
typedef struct _NwkNeighborInfoT NwkNeighborInfoT;
typedef struct _NwkRoutingInfoT NwkRoutingInfoT;
typedef struct _NwkZigbeeGenericCnf NwkZigbeeGenericCnf;
typedef struct _NwkZigbeeGenericRspInd NwkZigbeeGenericRspInd;
typedef struct _NwkZigbeeSystemResetReq NwkZigbeeSystemResetReq;
typedef struct _NwkZigbeeSystemResetCnf NwkZigbeeSystemResetCnf;
typedef struct _NwkZigbeeSystemSelfShutdownReq NwkZigbeeSystemSelfShutdownReq;
typedef struct _NwkSetZigbeePowerModeReq NwkSetZigbeePowerModeReq;
typedef struct _NwkSetZigbeePowerModeCnf NwkSetZigbeePowerModeCnf;
typedef struct _NwkGetLocalDeviceInfoReq NwkGetLocalDeviceInfoReq;
typedef struct _NwkStartCommissioningReq NwkStartCommissioningReq;
typedef struct _NwkSendSimpleDescriptorReq NwkSendSimpleDescriptorReq;
typedef struct _NwkSetInstallCodeReq NwkSetInstallCodeReq;
typedef struct _NwkGetLocalDeviceInfoCnf NwkGetLocalDeviceInfoCnf;
typedef struct _NwkGetGwEndpointInfoCnf NwkGetGwEndpointInfoCnf;
typedef struct _NwkZigbeeNwkReadyInd NwkZigbeeNwkReadyInd;
typedef struct _NwkZigbeeNwkInfoReq NwkZigbeeNwkInfoReq;
typedef struct _NwkZigbeeNwkInfoCnf NwkZigbeeNwkInfoCnf;
typedef struct _NwkSetPermitJoinReq NwkSetPermitJoinReq;
typedef struct _NwkManagePeriodicMtoRouteReq NwkManagePeriodicMtoRouteReq;
typedef struct _NwkGetNeighborTableReq NwkGetNeighborTableReq;
typedef struct _NwkGetNeighborTableRspInd NwkGetNeighborTableRspInd;
typedef struct _NwkGetRoutingTableReq NwkGetRoutingTableReq;
typedef struct _NwkGetRoutingTableRspInd NwkGetRoutingTableRspInd;
typedef struct _NwkChangeNwkKeyReq NwkChangeNwkKeyReq;
typedef struct _NwkGetNwkKeyReq NwkGetNwkKeyReq;
typedef struct _NwkGetNwkKeyCnf NwkGetNwkKeyCnf;
typedef struct _NwkZigbeeDeviceInd NwkZigbeeDeviceInd;
typedef struct _NwkGetDeviceListReq NwkGetDeviceListReq;
typedef struct _NwkGetDeviceListCnf NwkGetDeviceListCnf;
typedef struct _NwkDeviceListMaintenanceReq NwkDeviceListMaintenanceReq;
typedef struct _NwkRemoveDeviceReq NwkRemoveDeviceReq;
typedef struct _NwkSetBindingEntryReq NwkSetBindingEntryReq;
typedef struct _NwkSetBindingEntryRspInd NwkSetBindingEntryRspInd;
typedef struct _NwkGetBindingTableReq NwkGetBindingTableReq;
typedef struct _NwkGetBindingTableRspInd NwkGetBindingTableRspInd;
typedef struct _NwkSendSimpleDescriptorRspInd NwkSendSimpleDescriptorRspInd;
typedef struct _NwkBindItem NwkBindItem;
typedef struct _NwkAFAddr NwkAFAddr;


/* --- enums --- */

/*
 * MT System ID for Network Manager Protobuf sub-system ID
 */
typedef enum _ZStackNwkMgrSysIdT {
  Z_STACK_NWK_MGR_SYS_ID_T__RPC_SYS_PB_NWK_MGR = 18
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(Z_STACK_NWK_MGR_SYS_ID_T)
} ZStackNwkMgrSysIdT;
/*
 * Command IDs - each of these are associated with Request, Responses, Indications, and Confirm messages
 */
typedef enum _NwkMgrCmdIdT {
  NWK_MGR_CMD_ID_T__ZIGBEE_GENERIC_CNF = 0,
  NWK_MGR_CMD_ID_T__ZIGBEE_GENERIC_RSP_IND = 1,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_RESET_REQ = 2,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_RESET_CNF = 3,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_SELF_SHUTDOWN_REQ = 4,
  NWK_MGR_CMD_ID_T__NWK_SET_ZIGBEE_POWER_MODE_REQ = 5,
  NWK_MGR_CMD_ID_T__NWK_SET_ZIGBEE_POWER_MODE_CNF = 6,
  NWK_MGR_CMD_ID_T__NWK_GET_LOCAL_DEVICE_INFO_REQ = 7,
  NWK_MGR_CMD_ID_T__NWK_GET_LOCAL_DEVICE_INFO_CNF = 8,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_READY_IND = 9,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_INFO_REQ = 10,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_INFO_CNF = 11,
  NWK_MGR_CMD_ID_T__NWK_SET_PERMIT_JOIN_REQ = 12,
  NWK_MGR_CMD_ID_T__NWK_MANAGE_PERIODIC_MTO_ROUTE_REQ = 13,
  NWK_MGR_CMD_ID_T__NWK_GET_NEIGHBOR_TABLE_REQ = 14,
  NWK_MGR_CMD_ID_T__NWK_GET_NEIGHBOR_TABLE_RSP_IND = 15,
  NWK_MGR_CMD_ID_T__NWK_GET_ROUTING_TABLE_REQ = 16,
  NWK_MGR_CMD_ID_T__NWK_GET_ROUTING_TABLE_RSP_IND = 17,
  NWK_MGR_CMD_ID_T__NWK_CHANGE_NWK_KEY_REQ = 18,
  NWK_MGR_CMD_ID_T__NWK_GET_NWK_KEY_REQ = 19,
  NWK_MGR_CMD_ID_T__NWK_GET_NWK_KEY_CNF = 20,
  NWK_MGR_CMD_ID_T__NWK_ZIGBEE_DEVICE_IND = 21,
  NWK_MGR_CMD_ID_T__NWK_GET_DEVICE_LIST_REQ = 22,
  NWK_MGR_CMD_ID_T__NWK_GET_DEVICE_LIST_CNF = 23,
  NWK_MGR_CMD_ID_T__NWK_DEVICE_LIST_MAINTENANCE_REQ = 24,
  NWK_MGR_CMD_ID_T__NWK_REMOVE_DEVICE_REQ = 25,
  NWK_MGR_CMD_ID_T__NWK_SET_BINDING_ENTRY_REQ = 26,
  NWK_MGR_CMD_ID_T__NWK_SET_BINDING_ENTRY_RSP_IND = 27,
  NWK_MGR_CMD_ID_T__NWK_START_COMMISSIONING_REQ = 28,
  NWK_MGR_CMD_ID_T__NWK_START_COMMISSIONING_CNF = 29,
  NWK_MGR_CMD_ID_T__NWK_GET_BINDING_TABLE_REQ = 30,
  NWK_MGR_CMD_ID_T__NWK_GET_BINDING_TABLE_RSP_IND = 31,
  NWK_MGR_CMD_ID_T__NWK_SET_INSTALLCODE_REQ = 32,
  NWK_MGR_CMD_ID_T__NWK_GET_GW_ENDPOINT_INFO_REQ = 33,
  NWK_MGR_CMD_ID_T__NWK_GET_GW_ENDPOINT_INFO_CNF = 34,
  NWK_MGR_CMD_ID_T__NWK_SEND_SIMPLE_DESCRIPTOR_REQ = 35,
  NWK_MGR_CMD_ID_T__NWK_SEND_SIMPLE_DESCRIPTOR_RSP_IND = 36,
  NWK_MGR_CMD_ID_T__NWK_BIND_ITEM = 37
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_MGR_CMD_ID_T)
} NwkMgrCmdIdT;
typedef enum _NwkResetModeT {
  /*
   * Soft reset / maintain core stack base
   */
  NWK_RESET_MODE_T__SOFT_RESET = 0,
  /*
   * Hard reset / reset to factory new
   */
  NWK_RESET_MODE_T__HARD_RESET = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_RESET_MODE_T)
} NwkResetModeT;
typedef enum _NwkPowerModeT {
  /*
   * Sleep / low power mode
   */
  NWK_POWER_MODE_T__SLEEP = 0,
  /*
   * Wakeup / active mode
   */
  NWK_POWER_MODE_T__WAKEUP = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_POWER_MODE_T)
} NwkPowerModeT;
typedef enum _NwkNetworkStatusT {
  /*
   * Network down
   */
  NWK_NETWORK_STATUS_T__NWK_DOWN = 0,
  /*
   * Network up
   */
  NWK_NETWORK_STATUS_T__NWK_UP = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_NETWORK_STATUS_T)
} NwkNetworkStatusT;
typedef enum _NwkPermitJoinTypeT {
  /*
   * Sent to the local device only
   */
  NWK_PERMIT_JOIN_TYPE_T__PERMIT_LOCAL = 0,
  /*
   * Network wide (including this device)
   */
  NWK_PERMIT_JOIN_TYPE_T__PERMIT_NETWORK = 1,
  /*
   * Sent to all devices but this device
   */
  NWK_PERMIT_JOIN_TYPE_T__PERMIT_ALL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_PERMIT_JOIN_TYPE_T)
} NwkPermitJoinTypeT;
typedef enum _NwkMtoRouteModeT {
  /*
   * Start periodic MTO route request maintenance
   */
  NWK_MTO_ROUTE_MODE_T__MTO_ROUTE_START = 0,
  /*
   * Stop periodic MTO route request maintenance
   */
  NWK_MTO_ROUTE_MODE_T__MTO_ROUTE_STOP = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_MTO_ROUTE_MODE_T)
} NwkMtoRouteModeT;
typedef enum _NwkDeviceStatusT {
  /*
   * Device is off-line (non-responsive to service discovery)
   */
  NWK_DEVICE_STATUS_T__DEVICE_OFF_LINE = 0,
  /*
   * Status good
   */
  NWK_DEVICE_STATUS_T__DEVICE_ON_LINE = 1,
  /*
   * Device has been removed
   */
  NWK_DEVICE_STATUS_T__DEVICE_REMOVED = 2,
  /*
   * Not Applicable (this value is returned when gateway device)
   */
  NWK_DEVICE_STATUS_T__DEVICE_NA = 255
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_DEVICE_STATUS_T)
} NwkDeviceStatusT;
typedef enum _NwkAddressTypeT {
  /*
   * Unicast/Single device (using 64 bit IEEE Address)
   */
  NWK_ADDRESS_TYPE_T__UNICAST = 0,
  /*
   * Groupcast (using 16 bit group ID)
   */
  NWK_ADDRESS_TYPE_T__GROUPCAST = 1,
  /*
   * Broadcast (using 16 bit broacast address)
   */
  NWK_ADDRESS_TYPE_T__BROADCAST = 2,
  /*
   * Self addressing - referring to the gateway device itself. No address is specified
   */
  NWK_ADDRESS_TYPE_T__SELF = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_ADDRESS_TYPE_T)
} NwkAddressTypeT;
typedef enum _NwkStatusT {
  NWK_STATUS_T__STATUS_SUCCESS = 0,
  NWK_STATUS_T__STATUS_FAILURE = 1,
  /*
   * state machine busy, resources unavailable... 
   */
  NWK_STATUS_T__STATUS_BUSY = 2,
  NWK_STATUS_T__STATUS_INVALID_PARAMETER = 3,
  NWK_STATUS_T__STATUS_TIMEOUT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_STATUS_T)
} NwkStatusT;
typedef enum _NwkLeaveModeT {
  /*
   * Just Leave
   */
  NWK_LEAVE_MODE_T__LEAVE = 0,
  /*
   * Leave and rejoin
   */
  NWK_LEAVE_MODE_T__LEAVE_REJOIN = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_LEAVE_MODE_T)
} NwkLeaveModeT;
typedef enum _NwkBindingModeT {
  NWK_BINDING_MODE_T__BIND = 0,
  NWK_BINDING_MODE_T__UNBIND = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_BINDING_MODE_T)
} NwkBindingModeT;
typedef enum _NwkDeviceTypeT {
  NWK_DEVICE_TYPE_T__ZIGBEE_COORDINATOR = 0,
  NWK_DEVICE_TYPE_T__ZIGBEE_ROUTER = 1,
  NWK_DEVICE_TYPE_T__ZIGBEE_END_DEVICE = 2,
  NWK_DEVICE_TYPE_T__UNKNOWN_DEVICE_TYPE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_DEVICE_TYPE_T)
} NwkDeviceTypeT;
typedef enum _NwkRxOnWhenIdleT {
  NWK_RX_ON_WHEN_IDLE_T__RX_IS_OFF = 0,
  NWK_RX_ON_WHEN_IDLE_T__RX_IS_ON = 1,
  NWK_RX_ON_WHEN_IDLE_T__UNKNOWN_RX_STATE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_RX_ON_WHEN_IDLE_T)
} NwkRxOnWhenIdleT;
typedef enum _NwkRelationshipT {
  NWK_RELATIONSHIP_T__PARENT = 0,
  NWK_RELATIONSHIP_T__CHILD = 1,
  NWK_RELATIONSHIP_T__SIBLING = 2,
  NWK_RELATIONSHIP_T__NONE_OF_THE_ABOVE = 3,
  NWK_RELATIONSHIP_T__PREVIOUS_CHILD = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_RELATIONSHIP_T)
} NwkRelationshipT;
typedef enum _NwkPermitJoiningStatusT {
  NWK_PERMIT_JOINING_STATUS_T__NOT_ACCEPTING = 0,
  NWK_PERMIT_JOINING_STATUS_T__ACCEPTS = 1,
  NWK_PERMIT_JOINING_STATUS_T__UNKNOWN_STATUS = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_PERMIT_JOINING_STATUS_T)
} NwkPermitJoiningStatusT;
typedef enum _NwkRouteStatusT {
  NWK_ROUTE_STATUS_T__ROUTE_ACTIVE = 0,
  NWK_ROUTE_STATUS_T__ROUTE_DISCOVERY_UNDERWAY = 1,
  NWK_ROUTE_STATUS_T__ROUTE_DISCOVERY_FAILED = 2,
  NWK_ROUTE_STATUS_T__REOUT_INACTIVE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_ROUTE_STATUS_T)
} NwkRouteStatusT;
typedef enum _NwkAFAddrMode {
  NWK_AFADDR_MODE__NWK_AFADDR_MODE__NONE = 0,
  NWK_AFADDR_MODE__NWK_AFADDR_MODE__GROUP = 1,
  NWK_AFADDR_MODE__NWK_AFADDR_MODE__SHORT = 2,
  NWK_AFADDR_MODE__NWK_AFADDR_MODE__EXT = 3,
  NWK_AFADDR_MODE__NWK_AFADDR_MODE__BROADCAST = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NWK_AFADDR_MODE)
} NwkAFAddrMode;

/* --- messages --- */

/*
 *----------------------------------------------------------------------------------------------
 * Structures - submessages, these aren't sent as messages but are included within other messages
 *----------------------------------------------------------------------------------------------
 */
struct  _NwkGetGwEndpointInfoReq
{
  ProtobufCMessage base;
  NwkMgrCmdIdT cmdid;
};
#define NWK_GET_GW_ENDPOINT_INFO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_gw_endpoint_info_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_GW_ENDPOINT_INFO_REQ }


struct  _NwkAddressStructT
{
  ProtobufCMessage base;
  /*
   * Address Mode
   */
  NwkAddressTypeT addresstype;
  /*
   * Device's unique 64 bit IEEE Address (addressType == UNICAST)
   */
  protobuf_c_boolean has_ieeeaddr;
  uint64_t ieeeaddr;
  /*
   * (uint16) group address (addrMode == GROUPCAST)
   */
  protobuf_c_boolean has_groupaddr;
  uint32_t groupaddr;
  /*
   * (uint16) broadcast address (addrMode == BROADCAST)
   */
  protobuf_c_boolean has_broadcastaddr;
  uint32_t broadcastaddr;
  /*
   * (uint8) Endpoint ID. If omitted, it means referring to all endpoints.
   */
  protobuf_c_boolean has_endpointid;
  uint32_t endpointid;
};
#define NWK_ADDRESS_STRUCT_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_address_struct_t__descriptor) \
    , 0, 0,0, 0,0, 0,0, 0,0 }


struct  _NwkSimpleDescriptorT
{
  ProtobufCMessage base;
  /*
   * (uint8) endpoint
   */
  uint32_t endpointid;
  /*
   * (uint16) applications profile ID
   */
  uint32_t profileid;
  /*
   * (uint16) device ID
   */
  uint32_t deviceid;
  /*
   * (uint16) device version
   */
  uint32_t devicever;
  /*
   * Array of (uint16) input clusters
   */
  size_t n_inputclusters;
  uint32_t *inputclusters;
  /*
   * Array of (uint16) output clusters
   */
  size_t n_outputclusters;
  uint32_t *outputclusters;
};
#define NWK_SIMPLE_DESCRIPTOR_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_simple_descriptor_t__descriptor) \
    , 0, 0, 0, 0, 0,NULL, 0,NULL }


struct  _NwkBindRecT
{
  ProtobufCMessage base;
  /*
   * Source Address
   */
  NwkAddressStructT *srcaddr;
  /*
   * (uint16) Cluster ID
   */
  uint32_t clusterid;
  /*
   * destination address - target of the binding
   */
  NwkAddressStructT *dstaddr;
};
#define NWK_BIND_REC_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_bind_rec_t__descriptor) \
    , NULL, 0, NULL }


struct  _NwkDeviceInfoT
{
  ProtobufCMessage base;
  /*
   * (uint16) device short address
   */
  uint32_t networkaddress;
  /*
   * device extended address
   */
  uint64_t ieeeaddress;
  /*
   * IEEE address of the parent device, if available
   */
  protobuf_c_boolean has_parentieeeaddress;
  uint64_t parentieeeaddress;
  /*
   * (uint16) manufacturer ID
   */
  uint32_t manufacturerid;
  size_t n_simpledesclist;
  NwkSimpleDescriptorT **simpledesclist;
  NwkDeviceStatusT devicestatus;
};
#define NWK_DEVICE_INFO_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_device_info_t__descriptor) \
    , 0, 0, 0,0, 0, 0,NULL, 0 }


struct  _NwkNeighborInfoT
{
  ProtobufCMessage base;
  /*
   * Extended PAN ID of the neighbor device
   */
  uint64_t extendedpanid;
  /*
   * IEE Address
   */
  uint64_t extendedaddress;
  /*
   * (uint16) short Address
   */
  uint32_t networkaddress;
  /*
   * Device Type
   */
  NwkDeviceTypeT devicetype;
  /*
   * RxOnWhenIdle setting
   */
  NwkRxOnWhenIdleT idle;
  /*
   * Relationship
   */
  NwkRelationshipT relation;
  /*
   * Permit Joining status
   */
  NwkPermitJoiningStatusT permitjoining;
  /*
   * (uint8) The tree depth of the neighbor device
   */
  uint32_t depth;
  /*
   * (uint8) The estimated link quality for RF
   */
  uint32_t lqi;
};
#define NWK_NEIGHBOR_INFO_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_neighbor_info_t__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _NwkRoutingInfoT
{
  ProtobufCMessage base;
  /*
   * (uint16) network (short) address of the route destination
   */
  uint32_t dstaddr;
  /*
   * Route status
   */
  NwkRouteStatusT status;
  /*
   * (uint16) network address of the next hop in the route
   */
  uint32_t nexthop;
};
#define NWK_ROUTING_INFO_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_routing_info_t__descriptor) \
    , 0, 0, 0 }


struct  _NwkZigbeeGenericCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkStatusT status;
  /*
   * (uint16) transaction sequence number  
   */
  protobuf_c_boolean has_sequencenumber;
  uint32_t sequencenumber;
};
#define NWK_ZIGBEE_GENERIC_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_generic_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__ZIGBEE_GENERIC_CNF, 0, 0,0 }


struct  _NwkZigbeeGenericRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * (uint16) transaction sequence number  
   */
  uint32_t sequencenumber;
  NwkStatusT status;
};
#define NWK_ZIGBEE_GENERIC_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_generic_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__ZIGBEE_GENERIC_RSP_IND, 0, 0 }


struct  _NwkZigbeeSystemResetReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Reset mode  
   */
  NwkResetModeT mode;
};
#define NWK_ZIGBEE_SYSTEM_RESET_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_system_reset_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_RESET_REQ, 0 }


struct  _NwkZigbeeSystemResetCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkStatusT status;
  /*
   * reset mode 
   */
  NwkResetModeT resetmode;
};
#define NWK_ZIGBEE_SYSTEM_RESET_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_system_reset_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_RESET_CNF, 0, 0 }


struct  _NwkZigbeeSystemSelfShutdownReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
};
#define NWK_ZIGBEE_SYSTEM_SELF_SHUTDOWN_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_system_self_shutdown_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_SYSTEM_SELF_SHUTDOWN_REQ }


struct  _NwkSetZigbeePowerModeReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Power Mode type  
   */
  NwkPowerModeT powermode;
};
#define NWK_SET_ZIGBEE_POWER_MODE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_zigbee_power_mode_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_ZIGBEE_POWER_MODE_REQ, 0 }


struct  _NwkSetZigbeePowerModeCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkStatusT status;
  /*
   * Power Mode type  
   */
  NwkPowerModeT powermode;
};
#define NWK_SET_ZIGBEE_POWER_MODE_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_zigbee_power_mode_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_ZIGBEE_POWER_MODE_CNF, 0, 0 }


struct  _NwkGetLocalDeviceInfoReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
};
#define NWK_GET_LOCAL_DEVICE_INFO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_local_device_info_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_LOCAL_DEVICE_INFO_REQ }


struct  _NwkStartCommissioningReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Commissioning Mode
   */
  uint32_t commmode;
};
#define NWK_START_COMMISSIONING_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_start_commissioning_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_START_COMMISSIONING_REQ, 0 }


struct  _NwkSendSimpleDescriptorReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  uint32_t nwkaddr;
  uint32_t endpoint;
  uint32_t srcendpoint;
};
#define NWK_SEND_SIMPLE_DESCRIPTOR_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_send_simple_descriptor_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SEND_SIMPLE_DESCRIPTOR_REQ, 0, 0, 0 }


struct  _NwkSetInstallCodeReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  uint64_t ieeeaddress;
  size_t n_installcode;
  uint32_t *installcode;
  uint32_t crc;
};
#define NWK_SET_INSTALL_CODE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_install_code_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_INSTALLCODE_REQ, 0, 0,NULL, 0 }


struct  _NwkGetLocalDeviceInfoCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkDeviceInfoT *deviceinfolist;
};
#define NWK_GET_LOCAL_DEVICE_INFO_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_local_device_info_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_LOCAL_DEVICE_INFO_CNF, NULL }


struct  _NwkGetGwEndpointInfoCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkDeviceInfoT *deviceinfolist;
};
#define NWK_GET_GW_ENDPOINT_INFO_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_gw_endpoint_info_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_GW_ENDPOINT_INFO_CNF, NULL }


struct  _NwkZigbeeNwkReadyInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * (uint8) MAC Channel ID
   */
  uint32_t nwkchannel;
  /*
   * (uint16) Network PAN ID
   */
  uint32_t panid;
  /*
   * (uint64) Extended PAN ID
   */
  uint64_t extpanid;
};
#define NWK_ZIGBEE_NWK_READY_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_nwk_ready_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_READY_IND, 0, 0, 0 }


struct  _NwkZigbeeNwkInfoReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
};
#define NWK_ZIGBEE_NWK_INFO_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_nwk_info_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_INFO_REQ }


struct  _NwkZigbeeNwkInfoCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Network down/up
   */
  NwkNetworkStatusT status;
  /*
   * (uint8)  MAC Channel ID
   */
  uint32_t nwkchannel;
  /*
   * (uint16) Network PAN ID
   */
  uint32_t panid;
  /*
   * (uint64) extended PAN ID
   */
  uint64_t extpanid;
};
#define NWK_ZIGBEE_NWK_INFO_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_nwk_info_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_NWK_INFO_CNF, 0, 0, 0, 0 }


struct  _NwkSetPermitJoinReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Distribute of this request
   */
  NwkPermitJoinTypeT permitjoin;
  /*
   * (uint8) Duration in seconds to turn on Permit Join
   */
  uint32_t permitjointime;
};
#define NWK_SET_PERMIT_JOIN_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_permit_join_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_PERMIT_JOIN_REQ, 0, 0 }


struct  _NwkManagePeriodicMtoRouteReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkMtoRouteModeT mode;
};
#define NWK_MANAGE_PERIODIC_MTO_ROUTE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_manage_periodic_mto_route_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_MANAGE_PERIODIC_MTO_ROUTE_REQ, 0 }


struct  _NwkGetNeighborTableReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * destination address
   */
  NwkAddressStructT *dstaddr;
  /*
   * (uint8) Specifies where to start in the response array list.
   */
  uint32_t startindex;
};
#define NWK_GET_NEIGHBOR_TABLE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_neighbor_table_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_NEIGHBOR_TABLE_REQ, NULL, 0 }


struct  _NwkGetNeighborTableRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * (uint16) transaction sequence number
   */
  uint32_t sequencenumber;
  NwkStatusT status;
  /*
   * source address
   */
  NwkAddressStructT *srcaddr;
  /*
   * (uint8) Total number of entries available in the device
   */
  uint32_t neighbortableentries;
  /*
   * (uint8) Where in the total number of entries this response starts.
   */
  uint32_t startindex;
  /*
   * Array of neighbor info records
   */
  size_t n_neighborlist;
  NwkNeighborInfoT **neighborlist;
};
#define NWK_GET_NEIGHBOR_TABLE_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_neighbor_table_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_NEIGHBOR_TABLE_RSP_IND, 0, 0, NULL, 0, 0, 0,NULL }


struct  _NwkGetRoutingTableReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkAddressStructT *dstaddr;
  /*
   * (uint8) Specifies where to start in the response array list.
   */
  uint32_t startindex;
};
#define NWK_GET_ROUTING_TABLE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_routing_table_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_ROUTING_TABLE_REQ, NULL, 0 }


struct  _NwkGetRoutingTableRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * (uint16) transaction sequence number
   */
  uint32_t sequencenumber;
  /*
   * success/failure
   */
  NwkStatusT status;
  /*
   * source address
   */
  NwkAddressStructT *srcaddr;
  /*
   * (uint8) Total number of entries available in the device
   */
  uint32_t routingtableentries;
  /*
   * (uint8) Where in the total number of entries this response starts.
   */
  uint32_t startindex;
  /*
   * Array of routing info records
   */
  size_t n_routinglist;
  NwkRoutingInfoT **routinglist;
};
#define NWK_GET_ROUTING_TABLE_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_routing_table_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_ROUTING_TABLE_RSP_IND, 0, 0, NULL, 0, 0, 0,NULL }


struct  _NwkChangeNwkKeyReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * 16 bytes for network key
   */
  protobuf_c_boolean has_newkey;
  ProtobufCBinaryData newkey;
};
#define NWK_CHANGE_NWK_KEY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_change_nwk_key_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_CHANGE_NWK_KEY_REQ, 0,{0,NULL} }


struct  _NwkGetNwkKeyReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
};
#define NWK_GET_NWK_KEY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_nwk_key_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_NWK_KEY_REQ }


struct  _NwkGetNwkKeyCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkStatusT status;
  /*
   * 16 bytes for current active ZigBee network key
   */
  ProtobufCBinaryData newkey;
};
#define NWK_GET_NWK_KEY_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_nwk_key_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_NWK_KEY_CNF, 0, {0,NULL} }


struct  _NwkZigbeeDeviceInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * Device information
   */
  NwkDeviceInfoT *deviceinfo;
};
#define NWK_ZIGBEE_DEVICE_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_zigbee_device_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_ZIGBEE_DEVICE_IND, NULL }


struct  _NwkGetDeviceListReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * if included will return just this one device's 
   */
  NwkAddressStructT *dstaddr;
};
#define NWK_GET_DEVICE_LIST_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_device_list_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_DEVICE_LIST_REQ, NULL }


struct  _NwkGetDeviceListCnf
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  NwkStatusT status;
  /*
   * Device list information
   */
  size_t n_devicelist;
  NwkDeviceInfoT **devicelist;
};
#define NWK_GET_DEVICE_LIST_CNF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_device_list_cnf__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_DEVICE_LIST_CNF, 0, 0,NULL }


struct  _NwkDeviceListMaintenanceReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * if not included, send to all devices
   */
  NwkAddressStructT *dstaddr;
};
#define NWK_DEVICE_LIST_MAINTENANCE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_device_list_maintenance_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_DEVICE_LIST_MAINTENANCE_REQ, NULL }


struct  _NwkRemoveDeviceReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * address of device to be removed
   */
  NwkAddressStructT *dstaddr;
  NwkLeaveModeT leavemode;
};
#define NWK_REMOVE_DEVICE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_remove_device_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_REMOVE_DEVICE_REQ, NULL, 0 }


struct  _NwkSetBindingEntryReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * address of the node for initiating binding
   */
  NwkAddressStructT *srcaddr;
  /*
   * (uint16) cluster ID used to transport data between entries
   */
  uint32_t clusterid;
  /*
   * address of the target node for binding
   */
  NwkAddressStructT *dstaddr;
  NwkBindingModeT bindingmode;
};
#define NWK_SET_BINDING_ENTRY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_binding_entry_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_BINDING_ENTRY_REQ, NULL, 0, NULL, 0 }


struct  _NwkSetBindingEntryRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * (uint16) transaction sequence number
   */
  uint32_t sequencenumber;
  uint32_t status;
  /*
   * address of the node where the binding entry was created
   */
  NwkAddressStructT *srcaddr;
};
#define NWK_SET_BINDING_ENTRY_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_set_binding_entry_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SET_BINDING_ENTRY_RSP_IND, 0, 0, NULL }


struct  _NwkGetBindingTableReq
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * address of the node for initiating binding
   */
  NwkAddressStructT *dstaddr;
  uint32_t startindex;
};
#define NWK_GET_BINDING_TABLE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_binding_table_req__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_BINDING_TABLE_REQ, NULL, 0 }


struct  _NwkGetBindingTableRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * address of the node
   */
  uint32_t srcaddr;
  uint32_t status;
  /*
   * Number of binds
   */
  uint32_t bindentries;
  /*
   * Start index
   */
  uint32_t startindex;
  /*
   * List of binds
   */
  size_t n_bindlist;
  NwkBindItem **bindlist;
};
#define NWK_GET_BINDING_TABLE_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_get_binding_table_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_GET_BINDING_TABLE_RSP_IND, 0, 0, 0, 0, 0,NULL }


struct  _NwkSendSimpleDescriptorRspInd
{
  ProtobufCMessage base;
  /*
   * don't change this field
   */
  NwkMgrCmdIdT cmdid;
  /*
   * address of the node
   */
  uint32_t srcaddr;
  uint32_t status;
  uint32_t nwkaddrofinterest;
  NwkSimpleDescriptorT *simpledesc;
};
#define NWK_SEND_SIMPLE_DESCRIPTOR_RSP_IND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_send_simple_descriptor_rsp_ind__descriptor) \
    , NWK_MGR_CMD_ID_T__NWK_SEND_SIMPLE_DESCRIPTOR_RSP_IND, 0, 0, 0, NULL }


struct  _NwkBindItem
{
  ProtobufCMessage base;
  uint64_t srcaddr;
  uint32_t srcendpoint;
  uint32_t clustedid;
  NwkAFAddr *dstaddr;
};
#define NWK_BIND_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_bind_item__descriptor) \
    , 0, 0, 0, NULL }


struct  _NwkAFAddr
{
  ProtobufCMessage base;
  /*
   * Address Mode
   */
  NwkAddressTypeT addresstype;
  /*
   * extended address
   */
  protobuf_c_boolean has_ieeeaddr;
  uint64_t ieeeaddr;
  /*
   * (uint16)
   */
  protobuf_c_boolean has_groupaddr;
  uint32_t groupaddr;
  /*
   * (uint16)
   */
  protobuf_c_boolean has_broadcastaddr;
  uint32_t broadcastaddr;
  /*
   * (uint8)
   */
  protobuf_c_boolean has_endpointid;
  uint32_t endpointid;
  /*
   * (uint8)
   */
  protobuf_c_boolean has_gwendpointid;
  uint32_t gwendpointid;
};
#define NWK_AFADDR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nwk_afaddr__descriptor) \
    , 0, 0,0, 0,0, 0,0, 0,0, 0,0 }


/* NwkGetGwEndpointInfoReq methods */
void   nwk_get_gw_endpoint_info_req__init
                     (NwkGetGwEndpointInfoReq         *message);
size_t nwk_get_gw_endpoint_info_req__get_packed_size
                     (const NwkGetGwEndpointInfoReq   *message);
size_t nwk_get_gw_endpoint_info_req__pack
                     (const NwkGetGwEndpointInfoReq   *message,
                      uint8_t             *out);
size_t nwk_get_gw_endpoint_info_req__pack_to_buffer
                     (const NwkGetGwEndpointInfoReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetGwEndpointInfoReq *
       nwk_get_gw_endpoint_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_gw_endpoint_info_req__free_unpacked
                     (NwkGetGwEndpointInfoReq *message,
                      ProtobufCAllocator *allocator);
/* NwkAddressStructT methods */
void   nwk_address_struct_t__init
                     (NwkAddressStructT         *message);
size_t nwk_address_struct_t__get_packed_size
                     (const NwkAddressStructT   *message);
size_t nwk_address_struct_t__pack
                     (const NwkAddressStructT   *message,
                      uint8_t             *out);
size_t nwk_address_struct_t__pack_to_buffer
                     (const NwkAddressStructT   *message,
                      ProtobufCBuffer     *buffer);
NwkAddressStructT *
       nwk_address_struct_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_address_struct_t__free_unpacked
                     (NwkAddressStructT *message,
                      ProtobufCAllocator *allocator);
/* NwkSimpleDescriptorT methods */
void   nwk_simple_descriptor_t__init
                     (NwkSimpleDescriptorT         *message);
size_t nwk_simple_descriptor_t__get_packed_size
                     (const NwkSimpleDescriptorT   *message);
size_t nwk_simple_descriptor_t__pack
                     (const NwkSimpleDescriptorT   *message,
                      uint8_t             *out);
size_t nwk_simple_descriptor_t__pack_to_buffer
                     (const NwkSimpleDescriptorT   *message,
                      ProtobufCBuffer     *buffer);
NwkSimpleDescriptorT *
       nwk_simple_descriptor_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_simple_descriptor_t__free_unpacked
                     (NwkSimpleDescriptorT *message,
                      ProtobufCAllocator *allocator);
/* NwkBindRecT methods */
void   nwk_bind_rec_t__init
                     (NwkBindRecT         *message);
size_t nwk_bind_rec_t__get_packed_size
                     (const NwkBindRecT   *message);
size_t nwk_bind_rec_t__pack
                     (const NwkBindRecT   *message,
                      uint8_t             *out);
size_t nwk_bind_rec_t__pack_to_buffer
                     (const NwkBindRecT   *message,
                      ProtobufCBuffer     *buffer);
NwkBindRecT *
       nwk_bind_rec_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_bind_rec_t__free_unpacked
                     (NwkBindRecT *message,
                      ProtobufCAllocator *allocator);
/* NwkDeviceInfoT methods */
void   nwk_device_info_t__init
                     (NwkDeviceInfoT         *message);
size_t nwk_device_info_t__get_packed_size
                     (const NwkDeviceInfoT   *message);
size_t nwk_device_info_t__pack
                     (const NwkDeviceInfoT   *message,
                      uint8_t             *out);
size_t nwk_device_info_t__pack_to_buffer
                     (const NwkDeviceInfoT   *message,
                      ProtobufCBuffer     *buffer);
NwkDeviceInfoT *
       nwk_device_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_device_info_t__free_unpacked
                     (NwkDeviceInfoT *message,
                      ProtobufCAllocator *allocator);
/* NwkNeighborInfoT methods */
void   nwk_neighbor_info_t__init
                     (NwkNeighborInfoT         *message);
size_t nwk_neighbor_info_t__get_packed_size
                     (const NwkNeighborInfoT   *message);
size_t nwk_neighbor_info_t__pack
                     (const NwkNeighborInfoT   *message,
                      uint8_t             *out);
size_t nwk_neighbor_info_t__pack_to_buffer
                     (const NwkNeighborInfoT   *message,
                      ProtobufCBuffer     *buffer);
NwkNeighborInfoT *
       nwk_neighbor_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_neighbor_info_t__free_unpacked
                     (NwkNeighborInfoT *message,
                      ProtobufCAllocator *allocator);
/* NwkRoutingInfoT methods */
void   nwk_routing_info_t__init
                     (NwkRoutingInfoT         *message);
size_t nwk_routing_info_t__get_packed_size
                     (const NwkRoutingInfoT   *message);
size_t nwk_routing_info_t__pack
                     (const NwkRoutingInfoT   *message,
                      uint8_t             *out);
size_t nwk_routing_info_t__pack_to_buffer
                     (const NwkRoutingInfoT   *message,
                      ProtobufCBuffer     *buffer);
NwkRoutingInfoT *
       nwk_routing_info_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_routing_info_t__free_unpacked
                     (NwkRoutingInfoT *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeGenericCnf methods */
void   nwk_zigbee_generic_cnf__init
                     (NwkZigbeeGenericCnf         *message);
size_t nwk_zigbee_generic_cnf__get_packed_size
                     (const NwkZigbeeGenericCnf   *message);
size_t nwk_zigbee_generic_cnf__pack
                     (const NwkZigbeeGenericCnf   *message,
                      uint8_t             *out);
size_t nwk_zigbee_generic_cnf__pack_to_buffer
                     (const NwkZigbeeGenericCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeGenericCnf *
       nwk_zigbee_generic_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_generic_cnf__free_unpacked
                     (NwkZigbeeGenericCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeGenericRspInd methods */
void   nwk_zigbee_generic_rsp_ind__init
                     (NwkZigbeeGenericRspInd         *message);
size_t nwk_zigbee_generic_rsp_ind__get_packed_size
                     (const NwkZigbeeGenericRspInd   *message);
size_t nwk_zigbee_generic_rsp_ind__pack
                     (const NwkZigbeeGenericRspInd   *message,
                      uint8_t             *out);
size_t nwk_zigbee_generic_rsp_ind__pack_to_buffer
                     (const NwkZigbeeGenericRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeGenericRspInd *
       nwk_zigbee_generic_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_generic_rsp_ind__free_unpacked
                     (NwkZigbeeGenericRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeSystemResetReq methods */
void   nwk_zigbee_system_reset_req__init
                     (NwkZigbeeSystemResetReq         *message);
size_t nwk_zigbee_system_reset_req__get_packed_size
                     (const NwkZigbeeSystemResetReq   *message);
size_t nwk_zigbee_system_reset_req__pack
                     (const NwkZigbeeSystemResetReq   *message,
                      uint8_t             *out);
size_t nwk_zigbee_system_reset_req__pack_to_buffer
                     (const NwkZigbeeSystemResetReq   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeSystemResetReq *
       nwk_zigbee_system_reset_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_system_reset_req__free_unpacked
                     (NwkZigbeeSystemResetReq *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeSystemResetCnf methods */
void   nwk_zigbee_system_reset_cnf__init
                     (NwkZigbeeSystemResetCnf         *message);
size_t nwk_zigbee_system_reset_cnf__get_packed_size
                     (const NwkZigbeeSystemResetCnf   *message);
size_t nwk_zigbee_system_reset_cnf__pack
                     (const NwkZigbeeSystemResetCnf   *message,
                      uint8_t             *out);
size_t nwk_zigbee_system_reset_cnf__pack_to_buffer
                     (const NwkZigbeeSystemResetCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeSystemResetCnf *
       nwk_zigbee_system_reset_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_system_reset_cnf__free_unpacked
                     (NwkZigbeeSystemResetCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeSystemSelfShutdownReq methods */
void   nwk_zigbee_system_self_shutdown_req__init
                     (NwkZigbeeSystemSelfShutdownReq         *message);
size_t nwk_zigbee_system_self_shutdown_req__get_packed_size
                     (const NwkZigbeeSystemSelfShutdownReq   *message);
size_t nwk_zigbee_system_self_shutdown_req__pack
                     (const NwkZigbeeSystemSelfShutdownReq   *message,
                      uint8_t             *out);
size_t nwk_zigbee_system_self_shutdown_req__pack_to_buffer
                     (const NwkZigbeeSystemSelfShutdownReq   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeSystemSelfShutdownReq *
       nwk_zigbee_system_self_shutdown_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_system_self_shutdown_req__free_unpacked
                     (NwkZigbeeSystemSelfShutdownReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSetZigbeePowerModeReq methods */
void   nwk_set_zigbee_power_mode_req__init
                     (NwkSetZigbeePowerModeReq         *message);
size_t nwk_set_zigbee_power_mode_req__get_packed_size
                     (const NwkSetZigbeePowerModeReq   *message);
size_t nwk_set_zigbee_power_mode_req__pack
                     (const NwkSetZigbeePowerModeReq   *message,
                      uint8_t             *out);
size_t nwk_set_zigbee_power_mode_req__pack_to_buffer
                     (const NwkSetZigbeePowerModeReq   *message,
                      ProtobufCBuffer     *buffer);
NwkSetZigbeePowerModeReq *
       nwk_set_zigbee_power_mode_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_zigbee_power_mode_req__free_unpacked
                     (NwkSetZigbeePowerModeReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSetZigbeePowerModeCnf methods */
void   nwk_set_zigbee_power_mode_cnf__init
                     (NwkSetZigbeePowerModeCnf         *message);
size_t nwk_set_zigbee_power_mode_cnf__get_packed_size
                     (const NwkSetZigbeePowerModeCnf   *message);
size_t nwk_set_zigbee_power_mode_cnf__pack
                     (const NwkSetZigbeePowerModeCnf   *message,
                      uint8_t             *out);
size_t nwk_set_zigbee_power_mode_cnf__pack_to_buffer
                     (const NwkSetZigbeePowerModeCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkSetZigbeePowerModeCnf *
       nwk_set_zigbee_power_mode_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_zigbee_power_mode_cnf__free_unpacked
                     (NwkSetZigbeePowerModeCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkGetLocalDeviceInfoReq methods */
void   nwk_get_local_device_info_req__init
                     (NwkGetLocalDeviceInfoReq         *message);
size_t nwk_get_local_device_info_req__get_packed_size
                     (const NwkGetLocalDeviceInfoReq   *message);
size_t nwk_get_local_device_info_req__pack
                     (const NwkGetLocalDeviceInfoReq   *message,
                      uint8_t             *out);
size_t nwk_get_local_device_info_req__pack_to_buffer
                     (const NwkGetLocalDeviceInfoReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetLocalDeviceInfoReq *
       nwk_get_local_device_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_local_device_info_req__free_unpacked
                     (NwkGetLocalDeviceInfoReq *message,
                      ProtobufCAllocator *allocator);
/* NwkStartCommissioningReq methods */
void   nwk_start_commissioning_req__init
                     (NwkStartCommissioningReq         *message);
size_t nwk_start_commissioning_req__get_packed_size
                     (const NwkStartCommissioningReq   *message);
size_t nwk_start_commissioning_req__pack
                     (const NwkStartCommissioningReq   *message,
                      uint8_t             *out);
size_t nwk_start_commissioning_req__pack_to_buffer
                     (const NwkStartCommissioningReq   *message,
                      ProtobufCBuffer     *buffer);
NwkStartCommissioningReq *
       nwk_start_commissioning_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_start_commissioning_req__free_unpacked
                     (NwkStartCommissioningReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSendSimpleDescriptorReq methods */
void   nwk_send_simple_descriptor_req__init
                     (NwkSendSimpleDescriptorReq         *message);
size_t nwk_send_simple_descriptor_req__get_packed_size
                     (const NwkSendSimpleDescriptorReq   *message);
size_t nwk_send_simple_descriptor_req__pack
                     (const NwkSendSimpleDescriptorReq   *message,
                      uint8_t             *out);
size_t nwk_send_simple_descriptor_req__pack_to_buffer
                     (const NwkSendSimpleDescriptorReq   *message,
                      ProtobufCBuffer     *buffer);
NwkSendSimpleDescriptorReq *
       nwk_send_simple_descriptor_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_send_simple_descriptor_req__free_unpacked
                     (NwkSendSimpleDescriptorReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSetInstallCodeReq methods */
void   nwk_set_install_code_req__init
                     (NwkSetInstallCodeReq         *message);
size_t nwk_set_install_code_req__get_packed_size
                     (const NwkSetInstallCodeReq   *message);
size_t nwk_set_install_code_req__pack
                     (const NwkSetInstallCodeReq   *message,
                      uint8_t             *out);
size_t nwk_set_install_code_req__pack_to_buffer
                     (const NwkSetInstallCodeReq   *message,
                      ProtobufCBuffer     *buffer);
NwkSetInstallCodeReq *
       nwk_set_install_code_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_install_code_req__free_unpacked
                     (NwkSetInstallCodeReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetLocalDeviceInfoCnf methods */
void   nwk_get_local_device_info_cnf__init
                     (NwkGetLocalDeviceInfoCnf         *message);
size_t nwk_get_local_device_info_cnf__get_packed_size
                     (const NwkGetLocalDeviceInfoCnf   *message);
size_t nwk_get_local_device_info_cnf__pack
                     (const NwkGetLocalDeviceInfoCnf   *message,
                      uint8_t             *out);
size_t nwk_get_local_device_info_cnf__pack_to_buffer
                     (const NwkGetLocalDeviceInfoCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkGetLocalDeviceInfoCnf *
       nwk_get_local_device_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_local_device_info_cnf__free_unpacked
                     (NwkGetLocalDeviceInfoCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkGetGwEndpointInfoCnf methods */
void   nwk_get_gw_endpoint_info_cnf__init
                     (NwkGetGwEndpointInfoCnf         *message);
size_t nwk_get_gw_endpoint_info_cnf__get_packed_size
                     (const NwkGetGwEndpointInfoCnf   *message);
size_t nwk_get_gw_endpoint_info_cnf__pack
                     (const NwkGetGwEndpointInfoCnf   *message,
                      uint8_t             *out);
size_t nwk_get_gw_endpoint_info_cnf__pack_to_buffer
                     (const NwkGetGwEndpointInfoCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkGetGwEndpointInfoCnf *
       nwk_get_gw_endpoint_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_gw_endpoint_info_cnf__free_unpacked
                     (NwkGetGwEndpointInfoCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeNwkReadyInd methods */
void   nwk_zigbee_nwk_ready_ind__init
                     (NwkZigbeeNwkReadyInd         *message);
size_t nwk_zigbee_nwk_ready_ind__get_packed_size
                     (const NwkZigbeeNwkReadyInd   *message);
size_t nwk_zigbee_nwk_ready_ind__pack
                     (const NwkZigbeeNwkReadyInd   *message,
                      uint8_t             *out);
size_t nwk_zigbee_nwk_ready_ind__pack_to_buffer
                     (const NwkZigbeeNwkReadyInd   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeNwkReadyInd *
       nwk_zigbee_nwk_ready_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_nwk_ready_ind__free_unpacked
                     (NwkZigbeeNwkReadyInd *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeNwkInfoReq methods */
void   nwk_zigbee_nwk_info_req__init
                     (NwkZigbeeNwkInfoReq         *message);
size_t nwk_zigbee_nwk_info_req__get_packed_size
                     (const NwkZigbeeNwkInfoReq   *message);
size_t nwk_zigbee_nwk_info_req__pack
                     (const NwkZigbeeNwkInfoReq   *message,
                      uint8_t             *out);
size_t nwk_zigbee_nwk_info_req__pack_to_buffer
                     (const NwkZigbeeNwkInfoReq   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeNwkInfoReq *
       nwk_zigbee_nwk_info_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_nwk_info_req__free_unpacked
                     (NwkZigbeeNwkInfoReq *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeNwkInfoCnf methods */
void   nwk_zigbee_nwk_info_cnf__init
                     (NwkZigbeeNwkInfoCnf         *message);
size_t nwk_zigbee_nwk_info_cnf__get_packed_size
                     (const NwkZigbeeNwkInfoCnf   *message);
size_t nwk_zigbee_nwk_info_cnf__pack
                     (const NwkZigbeeNwkInfoCnf   *message,
                      uint8_t             *out);
size_t nwk_zigbee_nwk_info_cnf__pack_to_buffer
                     (const NwkZigbeeNwkInfoCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeNwkInfoCnf *
       nwk_zigbee_nwk_info_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_nwk_info_cnf__free_unpacked
                     (NwkZigbeeNwkInfoCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkSetPermitJoinReq methods */
void   nwk_set_permit_join_req__init
                     (NwkSetPermitJoinReq         *message);
size_t nwk_set_permit_join_req__get_packed_size
                     (const NwkSetPermitJoinReq   *message);
size_t nwk_set_permit_join_req__pack
                     (const NwkSetPermitJoinReq   *message,
                      uint8_t             *out);
size_t nwk_set_permit_join_req__pack_to_buffer
                     (const NwkSetPermitJoinReq   *message,
                      ProtobufCBuffer     *buffer);
NwkSetPermitJoinReq *
       nwk_set_permit_join_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_permit_join_req__free_unpacked
                     (NwkSetPermitJoinReq *message,
                      ProtobufCAllocator *allocator);
/* NwkManagePeriodicMtoRouteReq methods */
void   nwk_manage_periodic_mto_route_req__init
                     (NwkManagePeriodicMtoRouteReq         *message);
size_t nwk_manage_periodic_mto_route_req__get_packed_size
                     (const NwkManagePeriodicMtoRouteReq   *message);
size_t nwk_manage_periodic_mto_route_req__pack
                     (const NwkManagePeriodicMtoRouteReq   *message,
                      uint8_t             *out);
size_t nwk_manage_periodic_mto_route_req__pack_to_buffer
                     (const NwkManagePeriodicMtoRouteReq   *message,
                      ProtobufCBuffer     *buffer);
NwkManagePeriodicMtoRouteReq *
       nwk_manage_periodic_mto_route_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_manage_periodic_mto_route_req__free_unpacked
                     (NwkManagePeriodicMtoRouteReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetNeighborTableReq methods */
void   nwk_get_neighbor_table_req__init
                     (NwkGetNeighborTableReq         *message);
size_t nwk_get_neighbor_table_req__get_packed_size
                     (const NwkGetNeighborTableReq   *message);
size_t nwk_get_neighbor_table_req__pack
                     (const NwkGetNeighborTableReq   *message,
                      uint8_t             *out);
size_t nwk_get_neighbor_table_req__pack_to_buffer
                     (const NwkGetNeighborTableReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetNeighborTableReq *
       nwk_get_neighbor_table_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_neighbor_table_req__free_unpacked
                     (NwkGetNeighborTableReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetNeighborTableRspInd methods */
void   nwk_get_neighbor_table_rsp_ind__init
                     (NwkGetNeighborTableRspInd         *message);
size_t nwk_get_neighbor_table_rsp_ind__get_packed_size
                     (const NwkGetNeighborTableRspInd   *message);
size_t nwk_get_neighbor_table_rsp_ind__pack
                     (const NwkGetNeighborTableRspInd   *message,
                      uint8_t             *out);
size_t nwk_get_neighbor_table_rsp_ind__pack_to_buffer
                     (const NwkGetNeighborTableRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkGetNeighborTableRspInd *
       nwk_get_neighbor_table_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_neighbor_table_rsp_ind__free_unpacked
                     (NwkGetNeighborTableRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkGetRoutingTableReq methods */
void   nwk_get_routing_table_req__init
                     (NwkGetRoutingTableReq         *message);
size_t nwk_get_routing_table_req__get_packed_size
                     (const NwkGetRoutingTableReq   *message);
size_t nwk_get_routing_table_req__pack
                     (const NwkGetRoutingTableReq   *message,
                      uint8_t             *out);
size_t nwk_get_routing_table_req__pack_to_buffer
                     (const NwkGetRoutingTableReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetRoutingTableReq *
       nwk_get_routing_table_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_routing_table_req__free_unpacked
                     (NwkGetRoutingTableReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetRoutingTableRspInd methods */
void   nwk_get_routing_table_rsp_ind__init
                     (NwkGetRoutingTableRspInd         *message);
size_t nwk_get_routing_table_rsp_ind__get_packed_size
                     (const NwkGetRoutingTableRspInd   *message);
size_t nwk_get_routing_table_rsp_ind__pack
                     (const NwkGetRoutingTableRspInd   *message,
                      uint8_t             *out);
size_t nwk_get_routing_table_rsp_ind__pack_to_buffer
                     (const NwkGetRoutingTableRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkGetRoutingTableRspInd *
       nwk_get_routing_table_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_routing_table_rsp_ind__free_unpacked
                     (NwkGetRoutingTableRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkChangeNwkKeyReq methods */
void   nwk_change_nwk_key_req__init
                     (NwkChangeNwkKeyReq         *message);
size_t nwk_change_nwk_key_req__get_packed_size
                     (const NwkChangeNwkKeyReq   *message);
size_t nwk_change_nwk_key_req__pack
                     (const NwkChangeNwkKeyReq   *message,
                      uint8_t             *out);
size_t nwk_change_nwk_key_req__pack_to_buffer
                     (const NwkChangeNwkKeyReq   *message,
                      ProtobufCBuffer     *buffer);
NwkChangeNwkKeyReq *
       nwk_change_nwk_key_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_change_nwk_key_req__free_unpacked
                     (NwkChangeNwkKeyReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetNwkKeyReq methods */
void   nwk_get_nwk_key_req__init
                     (NwkGetNwkKeyReq         *message);
size_t nwk_get_nwk_key_req__get_packed_size
                     (const NwkGetNwkKeyReq   *message);
size_t nwk_get_nwk_key_req__pack
                     (const NwkGetNwkKeyReq   *message,
                      uint8_t             *out);
size_t nwk_get_nwk_key_req__pack_to_buffer
                     (const NwkGetNwkKeyReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetNwkKeyReq *
       nwk_get_nwk_key_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_nwk_key_req__free_unpacked
                     (NwkGetNwkKeyReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetNwkKeyCnf methods */
void   nwk_get_nwk_key_cnf__init
                     (NwkGetNwkKeyCnf         *message);
size_t nwk_get_nwk_key_cnf__get_packed_size
                     (const NwkGetNwkKeyCnf   *message);
size_t nwk_get_nwk_key_cnf__pack
                     (const NwkGetNwkKeyCnf   *message,
                      uint8_t             *out);
size_t nwk_get_nwk_key_cnf__pack_to_buffer
                     (const NwkGetNwkKeyCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkGetNwkKeyCnf *
       nwk_get_nwk_key_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_nwk_key_cnf__free_unpacked
                     (NwkGetNwkKeyCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkZigbeeDeviceInd methods */
void   nwk_zigbee_device_ind__init
                     (NwkZigbeeDeviceInd         *message);
size_t nwk_zigbee_device_ind__get_packed_size
                     (const NwkZigbeeDeviceInd   *message);
size_t nwk_zigbee_device_ind__pack
                     (const NwkZigbeeDeviceInd   *message,
                      uint8_t             *out);
size_t nwk_zigbee_device_ind__pack_to_buffer
                     (const NwkZigbeeDeviceInd   *message,
                      ProtobufCBuffer     *buffer);
NwkZigbeeDeviceInd *
       nwk_zigbee_device_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_zigbee_device_ind__free_unpacked
                     (NwkZigbeeDeviceInd *message,
                      ProtobufCAllocator *allocator);
/* NwkGetDeviceListReq methods */
void   nwk_get_device_list_req__init
                     (NwkGetDeviceListReq         *message);
size_t nwk_get_device_list_req__get_packed_size
                     (const NwkGetDeviceListReq   *message);
size_t nwk_get_device_list_req__pack
                     (const NwkGetDeviceListReq   *message,
                      uint8_t             *out);
size_t nwk_get_device_list_req__pack_to_buffer
                     (const NwkGetDeviceListReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetDeviceListReq *
       nwk_get_device_list_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_device_list_req__free_unpacked
                     (NwkGetDeviceListReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetDeviceListCnf methods */
void   nwk_get_device_list_cnf__init
                     (NwkGetDeviceListCnf         *message);
size_t nwk_get_device_list_cnf__get_packed_size
                     (const NwkGetDeviceListCnf   *message);
size_t nwk_get_device_list_cnf__pack
                     (const NwkGetDeviceListCnf   *message,
                      uint8_t             *out);
size_t nwk_get_device_list_cnf__pack_to_buffer
                     (const NwkGetDeviceListCnf   *message,
                      ProtobufCBuffer     *buffer);
NwkGetDeviceListCnf *
       nwk_get_device_list_cnf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_device_list_cnf__free_unpacked
                     (NwkGetDeviceListCnf *message,
                      ProtobufCAllocator *allocator);
/* NwkDeviceListMaintenanceReq methods */
void   nwk_device_list_maintenance_req__init
                     (NwkDeviceListMaintenanceReq         *message);
size_t nwk_device_list_maintenance_req__get_packed_size
                     (const NwkDeviceListMaintenanceReq   *message);
size_t nwk_device_list_maintenance_req__pack
                     (const NwkDeviceListMaintenanceReq   *message,
                      uint8_t             *out);
size_t nwk_device_list_maintenance_req__pack_to_buffer
                     (const NwkDeviceListMaintenanceReq   *message,
                      ProtobufCBuffer     *buffer);
NwkDeviceListMaintenanceReq *
       nwk_device_list_maintenance_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_device_list_maintenance_req__free_unpacked
                     (NwkDeviceListMaintenanceReq *message,
                      ProtobufCAllocator *allocator);
/* NwkRemoveDeviceReq methods */
void   nwk_remove_device_req__init
                     (NwkRemoveDeviceReq         *message);
size_t nwk_remove_device_req__get_packed_size
                     (const NwkRemoveDeviceReq   *message);
size_t nwk_remove_device_req__pack
                     (const NwkRemoveDeviceReq   *message,
                      uint8_t             *out);
size_t nwk_remove_device_req__pack_to_buffer
                     (const NwkRemoveDeviceReq   *message,
                      ProtobufCBuffer     *buffer);
NwkRemoveDeviceReq *
       nwk_remove_device_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_remove_device_req__free_unpacked
                     (NwkRemoveDeviceReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSetBindingEntryReq methods */
void   nwk_set_binding_entry_req__init
                     (NwkSetBindingEntryReq         *message);
size_t nwk_set_binding_entry_req__get_packed_size
                     (const NwkSetBindingEntryReq   *message);
size_t nwk_set_binding_entry_req__pack
                     (const NwkSetBindingEntryReq   *message,
                      uint8_t             *out);
size_t nwk_set_binding_entry_req__pack_to_buffer
                     (const NwkSetBindingEntryReq   *message,
                      ProtobufCBuffer     *buffer);
NwkSetBindingEntryReq *
       nwk_set_binding_entry_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_binding_entry_req__free_unpacked
                     (NwkSetBindingEntryReq *message,
                      ProtobufCAllocator *allocator);
/* NwkSetBindingEntryRspInd methods */
void   nwk_set_binding_entry_rsp_ind__init
                     (NwkSetBindingEntryRspInd         *message);
size_t nwk_set_binding_entry_rsp_ind__get_packed_size
                     (const NwkSetBindingEntryRspInd   *message);
size_t nwk_set_binding_entry_rsp_ind__pack
                     (const NwkSetBindingEntryRspInd   *message,
                      uint8_t             *out);
size_t nwk_set_binding_entry_rsp_ind__pack_to_buffer
                     (const NwkSetBindingEntryRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkSetBindingEntryRspInd *
       nwk_set_binding_entry_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_set_binding_entry_rsp_ind__free_unpacked
                     (NwkSetBindingEntryRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkGetBindingTableReq methods */
void   nwk_get_binding_table_req__init
                     (NwkGetBindingTableReq         *message);
size_t nwk_get_binding_table_req__get_packed_size
                     (const NwkGetBindingTableReq   *message);
size_t nwk_get_binding_table_req__pack
                     (const NwkGetBindingTableReq   *message,
                      uint8_t             *out);
size_t nwk_get_binding_table_req__pack_to_buffer
                     (const NwkGetBindingTableReq   *message,
                      ProtobufCBuffer     *buffer);
NwkGetBindingTableReq *
       nwk_get_binding_table_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_binding_table_req__free_unpacked
                     (NwkGetBindingTableReq *message,
                      ProtobufCAllocator *allocator);
/* NwkGetBindingTableRspInd methods */
void   nwk_get_binding_table_rsp_ind__init
                     (NwkGetBindingTableRspInd         *message);
size_t nwk_get_binding_table_rsp_ind__get_packed_size
                     (const NwkGetBindingTableRspInd   *message);
size_t nwk_get_binding_table_rsp_ind__pack
                     (const NwkGetBindingTableRspInd   *message,
                      uint8_t             *out);
size_t nwk_get_binding_table_rsp_ind__pack_to_buffer
                     (const NwkGetBindingTableRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkGetBindingTableRspInd *
       nwk_get_binding_table_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_get_binding_table_rsp_ind__free_unpacked
                     (NwkGetBindingTableRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkSendSimpleDescriptorRspInd methods */
void   nwk_send_simple_descriptor_rsp_ind__init
                     (NwkSendSimpleDescriptorRspInd         *message);
size_t nwk_send_simple_descriptor_rsp_ind__get_packed_size
                     (const NwkSendSimpleDescriptorRspInd   *message);
size_t nwk_send_simple_descriptor_rsp_ind__pack
                     (const NwkSendSimpleDescriptorRspInd   *message,
                      uint8_t             *out);
size_t nwk_send_simple_descriptor_rsp_ind__pack_to_buffer
                     (const NwkSendSimpleDescriptorRspInd   *message,
                      ProtobufCBuffer     *buffer);
NwkSendSimpleDescriptorRspInd *
       nwk_send_simple_descriptor_rsp_ind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_send_simple_descriptor_rsp_ind__free_unpacked
                     (NwkSendSimpleDescriptorRspInd *message,
                      ProtobufCAllocator *allocator);
/* NwkBindItem methods */
void   nwk_bind_item__init
                     (NwkBindItem         *message);
size_t nwk_bind_item__get_packed_size
                     (const NwkBindItem   *message);
size_t nwk_bind_item__pack
                     (const NwkBindItem   *message,
                      uint8_t             *out);
size_t nwk_bind_item__pack_to_buffer
                     (const NwkBindItem   *message,
                      ProtobufCBuffer     *buffer);
NwkBindItem *
       nwk_bind_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_bind_item__free_unpacked
                     (NwkBindItem *message,
                      ProtobufCAllocator *allocator);
/* NwkAFAddr methods */
void   nwk_afaddr__init
                     (NwkAFAddr         *message);
size_t nwk_afaddr__get_packed_size
                     (const NwkAFAddr   *message);
size_t nwk_afaddr__pack
                     (const NwkAFAddr   *message,
                      uint8_t             *out);
size_t nwk_afaddr__pack_to_buffer
                     (const NwkAFAddr   *message,
                      ProtobufCBuffer     *buffer);
NwkAFAddr *
       nwk_afaddr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nwk_afaddr__free_unpacked
                     (NwkAFAddr *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NwkGetGwEndpointInfoReq_Closure)
                 (const NwkGetGwEndpointInfoReq *message,
                  void *closure_data);
typedef void (*NwkAddressStructT_Closure)
                 (const NwkAddressStructT *message,
                  void *closure_data);
typedef void (*NwkSimpleDescriptorT_Closure)
                 (const NwkSimpleDescriptorT *message,
                  void *closure_data);
typedef void (*NwkBindRecT_Closure)
                 (const NwkBindRecT *message,
                  void *closure_data);
typedef void (*NwkDeviceInfoT_Closure)
                 (const NwkDeviceInfoT *message,
                  void *closure_data);
typedef void (*NwkNeighborInfoT_Closure)
                 (const NwkNeighborInfoT *message,
                  void *closure_data);
typedef void (*NwkRoutingInfoT_Closure)
                 (const NwkRoutingInfoT *message,
                  void *closure_data);
typedef void (*NwkZigbeeGenericCnf_Closure)
                 (const NwkZigbeeGenericCnf *message,
                  void *closure_data);
typedef void (*NwkZigbeeGenericRspInd_Closure)
                 (const NwkZigbeeGenericRspInd *message,
                  void *closure_data);
typedef void (*NwkZigbeeSystemResetReq_Closure)
                 (const NwkZigbeeSystemResetReq *message,
                  void *closure_data);
typedef void (*NwkZigbeeSystemResetCnf_Closure)
                 (const NwkZigbeeSystemResetCnf *message,
                  void *closure_data);
typedef void (*NwkZigbeeSystemSelfShutdownReq_Closure)
                 (const NwkZigbeeSystemSelfShutdownReq *message,
                  void *closure_data);
typedef void (*NwkSetZigbeePowerModeReq_Closure)
                 (const NwkSetZigbeePowerModeReq *message,
                  void *closure_data);
typedef void (*NwkSetZigbeePowerModeCnf_Closure)
                 (const NwkSetZigbeePowerModeCnf *message,
                  void *closure_data);
typedef void (*NwkGetLocalDeviceInfoReq_Closure)
                 (const NwkGetLocalDeviceInfoReq *message,
                  void *closure_data);
typedef void (*NwkStartCommissioningReq_Closure)
                 (const NwkStartCommissioningReq *message,
                  void *closure_data);
typedef void (*NwkSendSimpleDescriptorReq_Closure)
                 (const NwkSendSimpleDescriptorReq *message,
                  void *closure_data);
typedef void (*NwkSetInstallCodeReq_Closure)
                 (const NwkSetInstallCodeReq *message,
                  void *closure_data);
typedef void (*NwkGetLocalDeviceInfoCnf_Closure)
                 (const NwkGetLocalDeviceInfoCnf *message,
                  void *closure_data);
typedef void (*NwkGetGwEndpointInfoCnf_Closure)
                 (const NwkGetGwEndpointInfoCnf *message,
                  void *closure_data);
typedef void (*NwkZigbeeNwkReadyInd_Closure)
                 (const NwkZigbeeNwkReadyInd *message,
                  void *closure_data);
typedef void (*NwkZigbeeNwkInfoReq_Closure)
                 (const NwkZigbeeNwkInfoReq *message,
                  void *closure_data);
typedef void (*NwkZigbeeNwkInfoCnf_Closure)
                 (const NwkZigbeeNwkInfoCnf *message,
                  void *closure_data);
typedef void (*NwkSetPermitJoinReq_Closure)
                 (const NwkSetPermitJoinReq *message,
                  void *closure_data);
typedef void (*NwkManagePeriodicMtoRouteReq_Closure)
                 (const NwkManagePeriodicMtoRouteReq *message,
                  void *closure_data);
typedef void (*NwkGetNeighborTableReq_Closure)
                 (const NwkGetNeighborTableReq *message,
                  void *closure_data);
typedef void (*NwkGetNeighborTableRspInd_Closure)
                 (const NwkGetNeighborTableRspInd *message,
                  void *closure_data);
typedef void (*NwkGetRoutingTableReq_Closure)
                 (const NwkGetRoutingTableReq *message,
                  void *closure_data);
typedef void (*NwkGetRoutingTableRspInd_Closure)
                 (const NwkGetRoutingTableRspInd *message,
                  void *closure_data);
typedef void (*NwkChangeNwkKeyReq_Closure)
                 (const NwkChangeNwkKeyReq *message,
                  void *closure_data);
typedef void (*NwkGetNwkKeyReq_Closure)
                 (const NwkGetNwkKeyReq *message,
                  void *closure_data);
typedef void (*NwkGetNwkKeyCnf_Closure)
                 (const NwkGetNwkKeyCnf *message,
                  void *closure_data);
typedef void (*NwkZigbeeDeviceInd_Closure)
                 (const NwkZigbeeDeviceInd *message,
                  void *closure_data);
typedef void (*NwkGetDeviceListReq_Closure)
                 (const NwkGetDeviceListReq *message,
                  void *closure_data);
typedef void (*NwkGetDeviceListCnf_Closure)
                 (const NwkGetDeviceListCnf *message,
                  void *closure_data);
typedef void (*NwkDeviceListMaintenanceReq_Closure)
                 (const NwkDeviceListMaintenanceReq *message,
                  void *closure_data);
typedef void (*NwkRemoveDeviceReq_Closure)
                 (const NwkRemoveDeviceReq *message,
                  void *closure_data);
typedef void (*NwkSetBindingEntryReq_Closure)
                 (const NwkSetBindingEntryReq *message,
                  void *closure_data);
typedef void (*NwkSetBindingEntryRspInd_Closure)
                 (const NwkSetBindingEntryRspInd *message,
                  void *closure_data);
typedef void (*NwkGetBindingTableReq_Closure)
                 (const NwkGetBindingTableReq *message,
                  void *closure_data);
typedef void (*NwkGetBindingTableRspInd_Closure)
                 (const NwkGetBindingTableRspInd *message,
                  void *closure_data);
typedef void (*NwkSendSimpleDescriptorRspInd_Closure)
                 (const NwkSendSimpleDescriptorRspInd *message,
                  void *closure_data);
typedef void (*NwkBindItem_Closure)
                 (const NwkBindItem *message,
                  void *closure_data);
typedef void (*NwkAFAddr_Closure)
                 (const NwkAFAddr *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    z_stack_nwk_mgr_sys_id_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_mgr_cmd_id_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_reset_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_power_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_network_status_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_permit_join_type_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_mto_route_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_device_status_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_address_type_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_status_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_leave_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_binding_mode_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_device_type_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_rx_on_when_idle_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_relationship_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_permit_joining_status_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_route_status_t__descriptor;
extern const ProtobufCEnumDescriptor    nwk_afaddr_mode__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_gw_endpoint_info_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_address_struct_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_simple_descriptor_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_bind_rec_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_device_info_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_neighbor_info_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_routing_info_t__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_generic_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_generic_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_system_reset_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_system_reset_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_system_self_shutdown_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_zigbee_power_mode_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_zigbee_power_mode_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_local_device_info_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_start_commissioning_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_send_simple_descriptor_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_install_code_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_local_device_info_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_gw_endpoint_info_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_nwk_ready_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_nwk_info_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_nwk_info_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_permit_join_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_manage_periodic_mto_route_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_neighbor_table_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_neighbor_table_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_routing_table_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_routing_table_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_change_nwk_key_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_nwk_key_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_nwk_key_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_zigbee_device_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_device_list_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_device_list_cnf__descriptor;
extern const ProtobufCMessageDescriptor nwk_device_list_maintenance_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_remove_device_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_binding_entry_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_set_binding_entry_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_binding_table_req__descriptor;
extern const ProtobufCMessageDescriptor nwk_get_binding_table_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_send_simple_descriptor_rsp_ind__descriptor;
extern const ProtobufCMessageDescriptor nwk_bind_item__descriptor;
extern const ProtobufCMessageDescriptor nwk_afaddr__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_nwkmgr_2eproto__INCLUDED */
